//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodkickWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class comment
    {
        public int post_id { get; set; }
        public string user_id { get; set; }
        public Nullable<int> product_id { get; set; }
        public System.DateTime post_time { get; set; }
        public string post_content { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Product Product { get; set; }
    }
}
