//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GodkickWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product_Image
    {
        public int id { get; set; }
        public Nullable<int> product_id { get; set; }
        public string link_1 { get; set; }
        public string link_2 { get; set; }
        public string link_3 { get; set; }
        public string link_4 { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
